name: Build Cordova Android APK

on:
  workflow_dispatch: # so you can trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android platform
        run: cordova platform add android@10

      - name: Build release APK
        run: cordova build android --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: AviatorPro-APK
          path: platforms/android/app/build/outputs/apk/release/*.apk
