name: Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (OpenJDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova & Ionic CLI
        run: |
          npm install -g cordova
          npm install -g ionic

      - name: Install project dependencies
        run: npm install

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          script: echo "Android SDK ready"

      - name: Add Android platform
        run: cordova platform add android --no-interactive

      - name: Build release APK
        run: cordova build android --release --no-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: AviatorPro-APK
          path: platforms/android/app/build/outputs/apk/release/*.apk
